preprocess:
  load_dataset:
    filename: data/raw/villagers.csv
    features: ['Name', 'Species', 'Gender', 'Personality', 'Hobby', 'Birthday', 'Style_1', 'Style_2', 'Color_1', 'Color_2']
  feature_engineering:
    grouping_dict: {"ground_large" : 
                    ['Pig', 'Gorilla', 'Anteater', 'Bull',  'Horse', 'Kangaroo', 'Wolf','Elephant', 'Sheep', 'Deer', 'Tiger', 'Bear', 'Hippo', 'Lion', 'Rhino', 'Cow', 'Goat'],
                    "ground_small" : 
                    ['Squirrel', 'Koala', 'Mouse', 'Cat',  'Hamster', 'Penguin',  'Chicken','Cub', 'Dog',  'Ostrich', 'Rabbit', 'Monkey'],
                    "other": ['Alligator', 'Duck', 'Frog', 'Octopus', 'Bird', 'Eagle']}
  save_df: 
    output_path: data/interim/clean.csv

modeling:
  kmodes_modeling:
    filename: data/interim/clean.csv
    k_start: 1
    k_end: 30
    init: random
    n_init: 12
    random_state: 42
    pngpath: figures/cost_plot_kmodes.png

  recommendation:
    filename: data/interim/clean.csv
    n_cluster: 15
    init: random
    n_init: 12
    random_state: 42
    drop_list: ['Cluster', 'Species_villager', 'Gender_villager', 'Personality_villager', 'Hobby_villager', 'Birthday_villager', 'Style_1_villager', 'Style_2_villager', 'Color_1_villager', 'Color_2_villager']
    recommendation_path: data/final/recommendation.csv


